name: Move to "In Progress" when assigned

on:
  issues:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "In Progress"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectNumber = 6; // número do Project v2
            const org = "Vitor-Loli"; // org ou user
            const columnName = "In Progress";
          
            // Busca o ID do projeto e o campo "Status"
            const queryProject = `
              query($org: String!, $number: Int!) {
                user(login: $org) {
                  projectV2(number: $number) {
                    id
                    fields(first: 50) {
                      nodes {
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                        ... on ProjectV2SingleSelectField {
                          id
                          name
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }`;
          
            const { organization } = await github.graphql(queryProject, {
              org,
              number: projectNumber
            });
          
            const project = organization.projectV2;
            const statusField = project.fields.nodes.find(f => f.name === "Status");
            const option = statusField.options.find(o => o.name === columnName);
          
            // Busca o item do projeto associado à issue
            const queryIssue = `
              query($owner: String!, $repo: String!, $issue: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issue) {
                    id
                    projectItems(first: 20) {
                      nodes {
                        id
                        project {
                          number
                        }
                      }
                    }
                  }
                }
              }`;
          
            const { repository } = await github.graphql(queryIssue, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue: context.issue.number
            });
          
            const issue = repository.issue;
            const projectItem = issue.projectItems.nodes.find(p => p.project.number === projectNumber);
          
            if (!projectItem) {
              core.warning("Este issue ainda não está vinculado ao Project V2 especificado.");
              return;
            }
          
            // Atualiza o campo de status do item
            const mutation = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { singleSelectOptionId: $optionId }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }`;
          
            await github.graphql(mutation, {
              projectId: project.id,
              itemId: projectItem.id,
              fieldId: statusField.id,
              optionId: option.id
            });
          
            core.notice(`Issue movido para "${columnName}" com sucesso.`);
