name: Move to "In Progress" when assigned
on:
  issues:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "In Progress"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const columnName = "In Progress"; // nome da coluna (Status)
            const owner = "Vitor-Loli"; // dono do repositório
            const repoName = "ES2025-Grupo1-CervejariaBS"; // nome do repositório

            // 1️⃣ Pega os últimos Projects V2 abertos do repositório
            const queryProjects = `
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  projectsV2(first: 5, orderBy: {field: UPDATED_AT, direction: DESC}) {
                    nodes {
                      id
                      title
                      number
                      closed
                      fields(first: 50) {
                        nodes {
                          ... on ProjectV2SingleSelectField {
                            id
                            name
                            options {
                              id
                              name
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;

            const { repository } = await github.graphql(queryProjects, { owner, repo: repoName });
            const project = repository.projectsV2.nodes.find(p => !p.closed);

            if (!project) {
              core.warning("Nenhum ProjectV2 aberto encontrado para o repositório.");
              return;
            }

            const statusField = project.fields.nodes.find(f => f.name === "Status");
            if (!statusField) {
              core.warning("O campo 'Status' não foi encontrado neste Project.");
              return;
            }

            const option = statusField.options.find(o => o.name === columnName);
            if (!option) {
              core.warning(`A opção '${columnName}' não existe no campo Status.`);
              return;
            }

            // 2️⃣ Busca o item do projeto associado à issue
            const queryIssue = `
              query($owner: String!, $repo: String!, $issue: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issue) {
                    id
                    projectItems(first: 20) {
                      nodes {
                        id
                        project { id number }
                      }
                    }
                  }
                }
              }
            `;

            const { repository: repoData } = await github.graphql(queryIssue, { owner, repo: repoName, issue: context.issue.number });
            const issue = repoData.issue;
            const projectItem = issue.projectItems.nodes.find(p => p.project.id === project.id);

            if (!projectItem) {
              core.warning("Este issue ainda não está vinculado ao Project V2 encontrado.");
              return;
            }

            // 3️⃣ Atualiza o campo 'Status' para 'In Progress'
            const mutation = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: { 
                  projectId: $projectId, 
                  itemId: $itemId, 
                  fieldId: $fieldId, 
                  value: { singleSelectOptionId: $optionId } 
                }) {
                  projectV2Item { id }
                }
              }
            `;

            await github.graphql(mutation, {
              projectId: project.id,
              itemId: projectItem.id,
              fieldId: statusField.id,
              optionId: option.id,
            });

            core.notice(`✅ Issue movido para '${columnName}' no projeto '${project.title}'.`);
